### ISSUE TITLE
verifyAndDecodeNotification method throws error with status :1 

### ISSUE THREAD

**Issue by nikhil-icodelabs** [apple/app-store-server-library-node#204]
### Call Stack

![Screenshot 2024-09-17 at 6 30 20 PM](https://github.com/user-attachments/assets/99f8bcb8-60cc-4ea5-8154-42c0c4e4b8e5)

### Code Snippet

![Screenshot 2024-09-17 at 6 31 54 PM](https://github.com/user-attachments/assets/47be471c-fbd7-4447-8e23-fbf8543a3f86)

**Comment by KonstantinKostianytsia** [comment]
It works fine on my side. But I have the same problem with `verifyAndDecodeTransaction` function. 
I found that validation of decoded object fails because `validate` method receives `null`

<img width="547" alt="Screenshot 2024-09-26 at 19 45 46" src="https://github.com/user-attachments/assets/58444c3b-88c5-4c07-982a-f2feca88d96e">

**Comment by alexanderjordanbaker** [comment]
@KonstantinKostianytsia Are you sure what you are decoding is a signed transaction? Vs a notification or renewal info, for example

**Comment by KonstantinKostianytsia** [comment]
Yeah, you are right I have just checked my implementation and I passed `undefined` to that function. 
I passed `purchaseInfo.signedTransactionInfo` instead of `purchaseInfo.data.signedTransactionInfo`. 
So always write types for your variables.

About original issue. I can confirm that it works fine for me me.

**Comment by KonstantinKostianytsia** [comment]
@nikhil-icodelabs Are you sure you set Apple's CA certificates correctly?

**Comment by alexanderjordanbaker** [comment]
Hi all, are there any further questions here?
